### ISSUE TITLE
Firefox: ssl no cypher overlap

### ISSUE THREAD

**Issue by nickbetteridge** [anmonteiro/ocaml-h2#101]
Greetings! I just fired up examples/alpn/unix/alpn_server_tls using the given certificates and I'm getting a SSL_ERROR_NO_CYPHER_OVERLAP when using firefox on localhost:8080/9443. With chrome browser I'm getting an ERR_HTTP2_INADEQUATE_TRANSPORT_SECURITY

- do you have any ideas off the top of your head as to the problem before I start digging into this excellent piece of software :)

Thanks, Nick

**Comment by anmonteiro** [comment]
This is unfortunately expected. The HTTP/2 spec defines a list of [bad cipher suites](https://httpwg.org/specs/rfc7540.html#BadCipherSuites) that peers should not accept.

`ocaml-tls` is quite outdated in terms of ciphersuites and doesn't support elliptic curve ciphersuites or TLS 1.3 which is why you're getting that error.

If you try the OpenSSL examples those should work.

**Comment by nickbetteridge** [comment]
Ah, OK. Thanks for the feedback
