### ISSUE TITLE
Using your (ammonteiro) fork of httpaf

### ISSUE THREAD

**Issue by dgllghr** [anmonteiro/ocaml-h2#147]
Thank you for the many improvements to httpaf and for this http2 implementation! I would rather use your fork of httpaf (anmonteiro/httpaf) with its many improvements as part of this library. Is that supported?

**Comment by anmonteiro** [comment]
Hey! I appreciate you opening this issue.

I just saw your Github sponsorship come through and was looking for a way to contact you. Could you email me at `[my-username]@gmail.com` so that I can properly thank you for sponsoring my work?

I put lots of effort into my fork of http/af to be API compatible with upstream as much as possible, so it should be possible to use it as a drop-in with h2. In fact, that's what I do in [piaf](https://github.com/anmonteiro/piaf). You can depend on my fork of http/af from your preferred package manager and everything should work as expected.

**Comment by dgllghr** [comment]
Thanks, that's great to hear! I just sent you an email and am looking forward to staying in touch
